### ISSUE TITLE
Split TaxCalculator Business rules into its own Class Library

### ISSUE THREAD

**Issue by gjanecek** [GaryJanecek/MyCode#1]
The goal here is to allow the TaxCalculator business rules to be invoked from either a Winforms UI or a Console UI, or any other UI (i.e. Web, etc.)  We want the business rules to reside in a project isolated from all UI projects.
- [x] Create a New Console App (project) - TaxCalculatorConsole
- [x] Copy any console IO related classes to this new project
- [x] Create a new TaxCalculatorBusiness project as a Class Library
- [x] Copy TaxCalculator business classes to the TaxCalculatorBusiness library project
- [x] Remove TaxCalculator1 project from the solution (exclude first)

**Comment by gjanecek** [comment]
@peterjanecek 
Try to add a comment to this Issue to see if you have write access.
Also try to push your branch (AddTaxCalculatorSolution I think) to the repo with TortoiseGit.
1. In Cmder: git checkout AddTaxCalculatorSolution
2. In WindowsExplorer, right-mouse click, choose "Push", enter UN/Password if needed.
3. Add a comment to this issue to let me know if it worked.
Thanks

**Comment by peterjanecek** [comment]
Thanks. Trying that now, let's see what happens.

**Comment by peterjanecek** [comment]
fatal: Not a git repository

**Comment by gjanecek** [comment]
This has been merged already
